# Generated by Django 5.0.6 on 2024-05-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.BigIntegerField()),
                ('publication_date', models.DateField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
